### ISSUE TITLE
Improve yarn support

### ISSUE THREAD

**Issue by HaNdTriX** [webextension-toolbox/generator-web-extension#8]
Maybe we can detect if a user uses yarn and then install all deps via yarn.

## Todo

* [ ] Evaluate [has-yarn](https://github.com/sindresorhus/has-yarn)
* [ ] Use yarn to install deps http://yeoman.io/authoring/dependencies.html

**Comment by HaNdTriX** [comment]
For anyone who is interested. Yarn is working, but the default installer run npm.
If you want to use yarn just enter the following command after running `yo web-extension`:

```bash
$ rm package.lock.json && yarn
```

**Comment by balcsida** [comment]
What if we add an .npmrc file with
```
package-lock=false
```
content by default?

**Comment by HaNdTriX** [comment]
I believe we should not disable the `package-lock.json` or the `yarn.lock` file. 
I opened this issue because I thought, we might be able to detect, if a user uses yarn and then use `yarn install` instead of `npm install`.

https://github.com/webextension-toolbox/generator-web-extension/blob/master/app/index.js#L470

### Solution A

```js
const usesYarn = await commandExists('yarn')
if (usesYarn) {
  this.yarnInstall()
} else {
  this.npmInstall()
}
```

https://www.npmjs.com/package/command-exists

### Solution B

Ask the user what package manager he would like to use:

```js
if (this.answers.usesYarn) {
  this.yarnInstall()
} else {
  this.npmInstall()
}
```

What would you prefer. An some magic or an additional question (prompt)?
